/* --- LOONIX-TUNES src/audio/presets.rs --- */

#![allow(non_snake_case)]

#[derive(Clone)]
pub struct EqPreset {
    pub name: &'static str,
    pub gains: [f32; 10],
    pub preamp: f32,
    pub macro_val: f32,
}

#[derive(Clone)]
pub struct FxPreset {
    pub name: &'static str,
    pub bass_enabled: bool,
    pub bass_gain: f32,
    pub bass_cutoff: f32,
    pub bass_mode: i32,
    pub crystal_enabled: bool,
    pub crystal_amount: f32,
    pub crystal_freq: f32,
    pub surround_enabled: bool,
    pub surround_width: f32,
    pub mono_enabled: bool,
    pub mono_width: f32,
    pub pitch_enabled: bool,
    pub pitch_semitones: f32,
    pub middle_enabled: bool,
    pub middle_amount: f32,
    pub stereo_enabled: bool,
    pub stereo_amount: f32,
    pub crossfeed_enabled: bool,
    pub crossfeed_amount: f32,
    pub compressor_enabled: bool,
    pub compressor_threshold: f32,
}

pub const EQ_PRESETS: [EqPreset; 6] = [
    EqPreset {
        name: "LOONIX",
        gains: [3.0, 8.0, -5.0, 0.0, -3.0, -1.0, -3.0, -1.0, 1.0, -5.0],
        preamp: 0.0,
        macro_val: 0.0,
    },
    EqPreset {
        name: "BASS",
        gains: [6.0, 9.0, 0.0, -5.0, -5.0, -5.0, -5.0, -5.0, 2.0, -5.0],
        preamp: 0.0,
        macro_val: 0.0,
    },
    EqPreset {
        name: "ROCK",
        gains: [6.0, 9.0, 1.0, -2.0, -4.0, -2.0, 1.0, 3.0, 6.0, 6.0],
        preamp: 0.0,
        macro_val: 0.0,
    },
    EqPreset {
        name: "POP",
        gains: [-2.0, -1.0, 0.0, 2.0, 4.0, 0.0, 2.0, 0.0, -1.0, -2.0],
        preamp: 0.0,
        macro_val: 0.0,
    },
    EqPreset {
        name: "METAL",
        gains: [6.0, 10.0, 0.0, -4.0, -6.0, -4.0, 0.0, 3.0, 5.0, 6.0],
        preamp: 0.0,
        macro_val: 0.0,
    },
    EqPreset {
        name: "JAZZ",
        gains: [3.0, 2.0, 1.0, -2.0, -2.0, -2.0, -2.0, 1.0, 2.0, 3.0],
        preamp: 0.0,
        macro_val: 0.0,
    },
];

pub const FX_PRESETS: [FxPreset; 6] = [
    FxPreset {
        name: "LOONIX",
        bass_enabled: true,
        bass_gain: 6.0,
        bass_cutoff: 180.0,
        bass_mode: 2,
        crystal_enabled: true,
        crystal_amount: 0.5,
        crystal_freq: 8000.0,
        surround_enabled: true,
        surround_width: 1.5,
        mono_enabled: false,
        mono_width: 1.0,
        pitch_enabled: false,
        pitch_semitones: 0.0,
        middle_enabled: false,
        middle_amount: 0.0,
        stereo_enabled: true,
        stereo_amount: 0.4,
        crossfeed_enabled: false,
        crossfeed_amount: 0.0,
        compressor_enabled: true,
        compressor_threshold: -10.0,
    },
    FxPreset {
        name: "BASS BOOST",
        bass_enabled: true,
        bass_gain: 12.0,
        bass_cutoff: 180.0,
        bass_mode: 2,
        crystal_enabled: false,
        crystal_amount: 0.2,
        crystal_freq: 8000.0,
        surround_enabled: false,
        surround_width: 1.8,
        mono_enabled: false,
        mono_width: 1.0,
        pitch_enabled: false,
        pitch_semitones: 0.0,
        middle_enabled: false,
        middle_amount: 0.0,
        stereo_enabled: false,
        stereo_amount: 0.0,
        crossfeed_enabled: false,
        crossfeed_amount: 0.0,
        compressor_enabled: true,
        compressor_threshold: -8.0,
    },
    FxPreset {
        name: "LIVE",
        bass_enabled: true,
        bass_gain: 4.0,
        bass_cutoff: 180.0,
        bass_mode: 1,
        crystal_enabled: true,
        crystal_amount: 0.4,
        crystal_freq: 6000.0,
        surround_enabled: true,
        surround_width: 1.3,
        mono_enabled: false,
        mono_width: 1.0,
        pitch_enabled: false,
        pitch_semitones: 0.0,
        middle_enabled: true,
        middle_amount: 0.5,
        stereo_enabled: true,
        stereo_amount: 0.3,
        crossfeed_enabled: false,
        crossfeed_amount: 0.0,
        compressor_enabled: true,
        compressor_threshold: -12.0,
    },
    FxPreset {
        name: "STUDIO",
        bass_enabled: false,
        bass_gain: 0.0,
        bass_cutoff: 180.0,
        bass_mode: 0,
        crystal_enabled: false,
        crystal_amount: 0.0,
        crystal_freq: 4000.0,
        surround_enabled: false,
        surround_width: 1.0,
        mono_enabled: false,
        mono_width: 1.0,
        pitch_enabled: false,
        pitch_semitones: 0.0,
        middle_enabled: false,
        middle_amount: 0.0,
        stereo_enabled: false,
        stereo_amount: 0.0,
        crossfeed_enabled: false,
        crossfeed_amount: 0.0,
        compressor_enabled: false,
        compressor_threshold: -60.0,
    },
    FxPreset {
        name: "BINAURAL",
        bass_enabled: false,
        bass_gain: 0.0,
        bass_cutoff: 180.0,
        bass_mode: 0,
        crystal_enabled: false,
        crystal_amount: 0.0,
        crystal_freq: 4000.0,
        surround_enabled: false,
        surround_width: 1.0,
        mono_enabled: false,
        mono_width: 0.5,
        pitch_enabled: false,
        pitch_semitones: 0.0,
        middle_enabled: true,
        middle_amount: 0.8,
        stereo_enabled: false,
        stereo_amount: 0.0,
        crossfeed_enabled: true,
        crossfeed_amount: 0.5,
        compressor_enabled: false,
        compressor_threshold: -60.0,
    },
    FxPreset {
        name: "ACOUSTIC",
        bass_enabled: true,
        bass_gain: 3.0,
        bass_cutoff: 90.0,
        bass_mode: 0,
        crystal_enabled: true,
        crystal_amount: 0.3,
        crystal_freq: 4000.0,
        surround_enabled: true,
        surround_width: 1.2,
        mono_enabled: false,
        mono_width: 1.0,
        pitch_enabled: false,
        pitch_semitones: 0.0,
        middle_enabled: false,
        middle_amount: 0.0,
        stereo_enabled: true,
        stereo_amount: 0.2,
        crossfeed_enabled: false,
        crossfeed_amount: 0.0,
        compressor_enabled: true,
        compressor_threshold: -14.0,
    },
];

pub fn get_eq_preset(index: usize) -> Option<&'static EqPreset> {
    if index < EQ_PRESETS.len() {
        Some(&EQ_PRESETS[index])
    } else {
        None
    }
}

pub fn get_fx_preset(index: usize) -> Option<&'static FxPreset> {
    if index < FX_PRESETS.len() {
        Some(&FX_PRESETS[index])
    } else {
        None
    }
}
